default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  queue:
    <<: *default
    database: db/queue_development.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  queue:
    <<: *default
    database: db/queue_test.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: db/production.sqlite3
  queue:
    <<: *default
    database: db/queue_production.sqlite3
    migrations_paths: db/queue_migrate
